### ISSUE TITLE
Should the vital constructor do more type checking?

### ISSUE THREAD

**Issue by MilesMcBain** [robjhyndman/vital#44]
E.g. when Age is a character:

``` r
 library(vital)
#> Registered S3 method overwritten by 'tsibble':
#>   method               from 
#>   as_tibble.grouped_df dplyr
 library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.4.1
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
aus_mortality |>
  as_tibble() |>
  mutate(Age = as.character(Age)) |>
  vital(
   key = c(Age, Sex, State, Code),
   index = Year,
   .age = "Age"
  ) |>
  life_table()
#> Error in `purrr::map2()`:
#> ℹ In index: 1.
#> Caused by error in `round()`:
#> ! non-numeric argument to mathematical function
```

<sup>Created on 2024-11-29 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Could also verify `.sex` is a character or factor?

**Comment by robjhyndman** [comment]
Yes, more type checking would be good. If I wasn't building on top of the tsibble/fable packages, I would probably use S7 which requires type validation. But since I'm using S3 (mostly), putting type checking inside `vital()` and `as_vital()` is a step in the right direction.

**Comment by robjhyndman** [comment]
Addressed in https://github.com/robjhyndman/vital/commit/b018f63b9c39aab36c1216e578acc39a4f7a14d6
